name: Debug
on:
  pull_request:
    branches:
      - master
      - develop
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Update PR
        run: |
          echo '{"body":"https://google.github.io/site-kit-wp/storybook/${TARGET_DIR}/?path=*"}' | curl -vvv -H "Authorization: ${{ secrets.GITHUB_TOKEN }} OAUTH-TOKEN" -X PATCH --data-binary @- ${{ github.event.pull_request._links.issue.href }}
        env:
          TARGET_DIR: pull/2373
